version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.4
jobs:
  build:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - aws-s3/sync:
          from: dist
          to: 's3://byzombies-ci-cd-demo/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
  build-staging:
    docker:
      - image: circleci/python:2.7-node
    environment:
      AWS_REGION: us-east-1
    steps:
      - checkout
      - run: npm install
      - run: npm run build:staging
      - aws-s3/sync:
          from: dist
          to: 's3://byzombies-ci-cd-demo/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400" \
          overwrite: true
  test:
    docker:
      - image: circleci/python:2.7-node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
  build-staging:
    jobs:
      - build-staging:
          filters:
            branches:
              only: develop
  test:
    jobs:
      - test
